### ISSUE TITLE
icon styling

### ISSUE THREAD

**Issue by haileypate** [open-austin/open-data-progress-report#2]
The liaison icon seems more detailed and complex than the other 3 performance category icons. Any interest in finding something more simple, so as to harmonize the style a bit?

Maybe there's something usable in here: 
https://thenounproject.com/search/?q=employee&i=81096
https://thenounproject.com/search/?q=worker

**Comment by mateoclarke** [comment]
Cool, yeah I agree that the liaison icon is the most detailed and feels out of place comparatively. I also didn't want to fall into something super generic like a faceless man with a tie. 

I like the first one you linked. Here are a couple others. Let me know what you want to roll with:
https://thenounproject.com/term/user/17234/
https://thenounproject.com/term/user/11315/
https://thenounproject.com/term/user/130071/
