### ISSUE TITLE
other ways to use the card-style layout

### ISSUE THREAD

**Issue by haileypate** [open-austin/open-data-progress-report#3]
This layout also feels like a great way to tell a bigger story. I almost get the sense that the presentation is so grand that the simplicity of the performance items doesn't really do it justice. 

Matt E mentioned to me a few weeks ago that he thought it would be so cool if the City published a box (or card, whatever) for each dept that helps users get a sense for not only that dept's progress, but also its data goals and priorities. I feel like this prototype could easily head that direction as well. Not as a now thing... but maybe as a next or later thing.

**Comment by mateoclarke** [comment]
I was planning to work on a more stacked layout after @chip-rosenthal's [comment](https://github.com/open-austin/project-ideas/issues/23). I was thinking each row would be a department and the columns would be compliance status. Like a more traditional spreadsheet layout.

But I like the card layout too and think you're right that it is probably more effective if there is more content on each card.

**Comment by haileypate** [comment]
The card layout is awesome... seriously... I can't wait for when Matt E sees it. Def keep it simmering, because I'm sure the team will have all kinds of ideas for leveraging it. 

I really like the idea of the stacked layout. I also love how the 4 icons are repeated for each dataset. Would be great to preserve that look and feel somehow if you go with a stacked thing.

**Comment by mateoclarke** [comment]
Here are links for the two layout options:
- [Stacked rows](http://open-austin.github.io/open-data-progress-report/alt-version.html)
- [Cards](http://open-austin.github.io/open-data-progress-report/index.html)

Let me know what you wanna roll with...

**Comment by haileypate** [comment]
Stacked rows  :)
