### ISSUE TITLE
embedding at austintexas.gov

### ISSUE THREAD

**Issue by haileypate** [open-austin/open-data-progress-report#4]
Any thoughts or interest in exploring how this content might be styled to fit in as main content on austintexas.gov? Like as if it were to be framed by the City website nav bars, footer, etc?

**Comment by mateoclarke** [comment]
Yeah certainly, can you share a link to an example page that would most likely have all the components that would frame the main content?

I'm seeing several layouts at different links within the city site:
http://austintexas.gov/blog/wrap-texas-digital-government-summit (only right sidebar)
http://austintexas.gov/department/austin-hacks (left and right sidebars)
http://austintexas.gov/news/prescribed-burn-helps-restore-native-grasslands (only left sidebar)

**Comment by haileypate** [comment]
yes, I will ask the team about this at work tomorrow. thank you for providing those example links!

**Comment by haileypate** [comment]
Showed this to the team at today's weekly data portal gathering... they really like where this is going! Their favorite of the two layouts is the table version. One idea kicked around was to embed as an iframe at the open gov section of austintexas.gov, with attribution to Open Austin. Here's why...

Matt E brought up a great point today in the meeting. Having the report originate from a place outside government increases the "checks and balances" on this initiative. When the facts are reported by Open Austin and others, especially in a way that makes the code and discussions publicly accessible in a repo like this, that's the kind of transparency that fosters credibility. I'm probably butchering what he said..  but it sounded really cool when he said it. 

So to that end, we might get more value from embedding the table and description as an iframe versus forking the code. If that would work well for y'all. Divya, a manager from our web services team, is having one of her programmers look at options on our end. I'll reach out to that person (whom I may not have met yet!) and see how to best connect y'all. Ball still in my court. Over and out!

**Comment by haileypate** [comment]
Alex from the web services team has staged a demo page for us that has the code embedded as an iframe... it's on our internal server and i don't know how to view it yet. we will need to figure that out. in the meantime, here is a screenshot for discussion. https://drive.google.com/open?id=0ByH6oExoXJ0KMWl1RG5QSnp2VFk

**Comment by haileypate** [comment]
@mateoclarke to answer your original question... i guess the decision got made for us! we'll need a way to test said layout per the launch checklist. will open a new issue re testing...
