### ISSUE TITLE
More Dept Icons

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/open-data-progress-report#7]
We need more SVG icons to represent departments. We have been sourcing icons from the [thenounproject.com](https://thenounproject.com/). Make sure to download the SVG version _(it scales better for retina display devices)_.
- [x] Aviation
- [ ] Planning and Zoning Development Services
- [x] Emergency Medical Services
- [x] Financial Services
- [x] Fire
- [ ] Fleet Services
- [x] Government Relations
- [x] Health and Human Services
- [ ] Homeland Security & Emergency Management
- [ ] Human Resources
- [x] Law
- [ ] Municipal Court
- [x] Neighborhood Housing and Community Development
- [x] Office of Real Estate Services
- [ ] Office of Sustainability
- [ ] Office of the City Auditor
- [ ] Office of the City Clerk
- [ ] Office of the Medical Director
- [x] Parks and Recreation
- [ ] Police
- [ ] Public Works
- [ ] Small and Minority Business Resources
- [ ] Telecommunications & Regulatory Affairs
- [ ] Watershed Protection

**Comment by haileypate** [comment]
cool... i didn't know you could make checkboxes like that :smiley:

**Comment by mateoclarke** [comment]
oh yeah! 
https://guides.github.com/features/mastering-markdown/#examples

Search for "Task Lists"

**Comment by mateoclarke** [comment]
-[x]

**Comment by carissamelanson** [comment]
I just created a pull request to add a fire.svg and a neighborhood-housing-and-community-development.svg
